import { useCallback, useEffect, useMemo, useState } from 'react';
import { ROLE_LABEL, todayEat, formatDateLabel } from './api';
import { usePagination } from './Pagination';
import { useSort } from './useSort';
import { useBusy, useToast } from './toast';
import { recalcNotice, recalcResult, useConfirm } from './confirm';

// Roles that never have a worker record: UCAA auditors (and the Director
// role, when added) aren't casual workers.
const NO_WORKER_LINK = ['director', 'auditor'];

const workerLabel = (w) => `${w.name} (${w.biostarUserId})`;

// Search box over worker records; calls onPick(worker | null).
function WorkerPicker({ workers, value, onPick, placeholder, id }) {
  const [text, setText] = useState(value ? workerLabel(value) : '');
  useEffect(() => { setText(value ? workerLabel(value) : ''); }, [value]);
  return (
    <>
      <input
        list={id}
        value={text}
        placeholder={placeholder}
        onChange={(e) => {
          setText(e.target.value);
          onPick(workers.find((w) => workerLabel(w) === e.target.value.trim()) || null);
        }}
      />
      <datalist id={id}>
        {workers.map((w) => <option key={w.id} value={workerLabel(w)} />)}
      </datalist>
    </>
  );
}

// Temporary passwords are generated by the server and emailed to the
// account holder. Only when that email fails does the server hand the
// password back — shown here once, to pass on another way.
function showTemporaryPassword(confirm, { email, password, emailError }) {
  return confirm({
    title: 'The email couldn’t be sent',
    body: (
      <>
        <p>The sign-in email to <strong>{email}</strong> failed ({emailError}). Give them this temporary password another way — by phone or in person, not in a group chat:</p>
        <p className="temp-password" aria-label="Temporary password">{password}</p>
        <p>It’s shown only this once. They’ll have to choose their own password when they first sign in. If it’s lost, use “Send new temporary password”.</p>
      </>
    ),
    confirmLabel: 'Done',
    cancelLabel: null
  });
}

function UserRow({ api, account, crews, freeWorkers, workersById, canEdit, canDisable, onSaved }) {
  const [editing, setEditing] = useState(false);
  const [linkTo, setLinkTo] = useState(null);
  const [moveTo, setMoveTo] = useState('');
  const [moveFrom, setMoveFrom] = useState(todayEat());
  const [confirmMove, setConfirmMove] = useState(false);
  const [error, setError] = useState('');
  const toast = useToast();
  const confirm = useConfirm();
  const { guard, busy } = useBusy();
  const isSupervisor = account.role === 'supervisor';
  const isAdminAccount = account.role === 'sysadmin';
  const linkedWorker = account.casualWorkerId ? workersById.get(account.casualWorkerId) : null;
  const who = account.name || account.email;

  // One change at a time per account; on success the panel closes, the
  // form clears and the list reloads; on failure the panel stays open with
  // what was entered, so it can be corrected and tried again.
  function patch(body, successMessage) {
    return guard(async () => {
      setError('');
      try {
        const result = await api(`/api/users/${account.id}`, { method: 'PATCH', body });
        if (result.emailed === false) {
          toast.warn(`New temporary password set for ${who}, but the email couldn’t be sent.`);
          await showTemporaryPassword(confirm, { email: account.email, password: result.temporaryPassword, emailError: result.emailError });
        } else {
          toast.success(result.emailed
            ? `A new temporary password has been emailed to ${account.email}.`
            : `${successMessage}${result.recalculated ? recalcResult(result.recalculated) : ''}`);
        }
        setEditing(false);
        setLinkTo(null);
        setConfirmMove(false);
        onSaved();
      } catch (err) {
        setError(err.message);
        toast.error(`Couldn’t update ${who}: ${err.message}`);
      }
    });
  }

  async function sendNewPassword() {
    const ok = await confirm({
      title: `Send ${who} a new temporary password?`,
      body: <p>Their current password stops working straight away. A new one is emailed to <strong>{account.email}</strong>, and they’ll choose their own when they next sign in.{isAdminAccount ? ' All System Admins are told, since this is a System Admin account.' : ''}</p>,
      confirmLabel: 'Send new password'
    });
    if (ok) patch({ resetPassword: true }, `New temporary password sent to ${who}.`);
  }

  async function toggleActive() {
    if (account.active) {
      const ok = await confirm({
        title: `Disable ${who}’s account?`,
        body: <p>They’re signed out straight away and can’t sign in until it’s re-enabled.{isAdminAccount ? ' All System Admins are told, since this is a System Admin account.' : ''}</p>,
        confirmLabel: 'Disable account',
        danger: true
      });
      if (!ok) return;
    }
    patch({ active: !account.active }, account.active ? `${who}’s account has been disabled.` : `${who}’s account has been re-enabled.`);
  }

  const targetCrew = crews.find((c) => String(c.id) === String(moveTo));

  return (
    <tr>
      <td>
        <div style={{ fontWeight: 600 }}>{account.name || '—'}{!account.active && <span className="chip chip--critical" style={{ marginLeft: 8 }}>disabled</span>}
          {account.active && account.mustChangePassword && <span className="chip chip--warn" style={{ marginLeft: 8 }} title="Still on the password they were given — they'll choose their own at their next sign-in.">temporary password</span>}</div>
        {account.worker
          ? <div className="small muted">Worker {account.worker.biostarUserId}{account.worker.status !== 'active' && ' · inactive in BioStar'}</div>
          : <div className="small muted">No worker record</div>}
      </td>
      <td className="small">{account.email}</td>
      <td>{ROLE_LABEL[account.role] || account.role}</td>
      <td>{account.crew?.name || '—'}</td>
      <td>
        {canEdit && !editing && <button className="btn btn--small" onClick={() => setEditing(true)}>Manage</button>}
        {editing && (
          <div className="manage">
            {isSupervisor && (
              <div className="manage__block">
                <div className="manage__label">Move to another crew</div>
                <p className="small muted" style={{ margin: '0 0 8px' }}>
                  A supervisor leads the crew they rotate with, so this also moves {linkedWorker ? linkedWorker.name : 'their worker record'} onto that crew’s cycle.
                </p>
                {!confirmMove ? (
                  <div className="form-row">
                    <select className="input" value={moveTo} onChange={(e) => setMoveTo(e.target.value)}>
                      <option value="">Choose crew…</option>
                      {crews.filter((c) => c.id !== account.crewId).map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
                    </select>
                    <input className="input" type="date" value={moveFrom} onChange={(e) => setMoveFrom(e.target.value)} title="From" />
                    <button className="btn btn--small" disabled={!moveTo} onClick={() => setConfirmMove(true)}>Move…</button>
                  </div>
                ) : (
                  <div className="decision">
                    <div className="decision__title">Move {account.name} to {targetCrew?.name}?</div>
                    <p className="decision__body">
                      From {formatDateLabel(moveFrom)} they rotate with <strong>{targetCrew?.name}</strong> and become its supervisor.
                      {account.crew ? ` ${account.crew.name} will need a new supervisor.` : ''} To take them off supervising instead, change their schedule in Schedules → Workers.
                    </p>
                    <p className="decision__body">{recalcNotice(`${account.name}’s`, moveFrom)}</p>
                    <div className="decision__actions">
                      <button className="btn btn--primary btn--small" disabled={busy} onClick={() => patch({ moveToCrewId: Number(moveTo), effectiveFrom: moveFrom }, `${who} moved to ${targetCrew?.name} from ${formatDateLabel(moveFrom)}.`)}>{busy ? 'Moving…' : 'Yes, move them'}</button>
                      <button className="btn btn--link small" onClick={() => setConfirmMove(false)}>Cancel</button>
                    </div>
                  </div>
                )}
              </div>
            )}

            {!isSupervisor && !NO_WORKER_LINK.includes(account.role) && (
              <div className="manage__block">
                <div className="manage__label">Worker record</div>
                {account.worker ? (
                  <div className="form-row">
                    <span className="small">{workerLabel(account.worker)}</span>
                    <button className="btn btn--small" disabled={busy} onClick={() => patch({ casualWorkerId: null }, `${who} is no longer linked to a worker record.`)}>Unlink</button>
                  </div>
                ) : (
                  <div className="form-row">
                    <label className="field field--grow">
                      <WorkerPicker id={`link-${account.id}`} workers={freeWorkers} value={linkTo} onPick={setLinkTo} placeholder="Search a name or ID…" />
                    </label>
                    <button className="btn btn--small" disabled={!linkTo || busy} onClick={() => patch({ casualWorkerId: linkTo.id }, `${who} linked to ${linkTo.name}.`)}>Link</button>
                  </div>
                )}
              </div>
            )}

            <div className="manage__block">
              <div className="manage__label">Password</div>
              <div className="form-row">
                <button className="btn btn--small" disabled={busy} onClick={sendNewPassword}>{busy ? 'Sending…' : 'Send new temporary password'}</button>
              </div>
              <p className="small muted" style={{ margin: '6px 0 0' }}>The portal makes one up and emails it to {account.email} — no one else sees it. Their current password stops working, and they choose their own at their next sign-in.</p>
            </div>
            <div className="form-row" style={{ marginTop: 10 }}>
              <button
                className={`btn btn--small ${account.active ? 'btn--danger' : ''}`}
                disabled={busy || (account.active && !canDisable)}
                title={account.active && !canDisable ? 'The only active System Admin can’t be disabled. Make someone else a System Admin first.' : undefined}
                onClick={toggleActive}
              >
                {account.active ? 'Disable account' : 'Re-enable account'}
              </button>
              <button className="btn btn--link small" onClick={() => { setEditing(false); setConfirmMove(false); setError(''); }}>Close</button>
            </div>
            {error && <div className="error">{error}</div>}
          </div>
        )}
      </td>
    </tr>
  );
}

export default function UsersPage({ api, user }) {
  const [users, setUsers] = useState([]);
  const [canCreate, setCanCreate] = useState([]);
  const [crews, setCrews] = useState([]);
  const [workers, setWorkers] = useState([]);
  const [form, setForm] = useState({ name: '', email: '', role: '' });
  const [worker, setWorker] = useState(null);
  const [error, setError] = useState('');
  const toast = useToast();
  const confirm = useConfirm();
  const { guard, busy: creating } = useBusy();
  const activeAdmins = users.filter((u) => u.role === 'sysadmin' && u.active).length;
  const { sorted: sortedUsers, th, sortKey } = useSort(users, {
    name: (u) => u.name,
    email: (u) => u.email,
    role: (u) => ROLE_LABEL[u.role] || u.role,
    crew: (u) => u.crew?.name
  });
  const { pageItems: pageUsers, pager } = usePagination(sortedUsers, { id: 'users', defaultSize: 25, noun: 'accounts', resetKey: sortKey });

  const load = useCallback(() => {
    api('/api/users')
      .then((d) => {
        setUsers(d.users);
        setCanCreate(d.canCreate);
        setForm((f) => ({ ...f, role: f.role || d.canCreate[0] || '' }));
      })
      .catch((err) => setError(err.message));
    api('/api/crews').then((d) => setCrews(d.crews)).catch(() => {});
    api('/api/workers').then((d) => setWorkers(d.workers)).catch(() => {});
  }, [api]);

  useEffect(() => { load(); }, [load]);

  const workersById = useMemo(() => new Map(workers.map((w) => [w.id, w])), [workers]);
  // Active workers not already linked to an account.
  const freeWorkers = useMemo(() => {
    const linked = new Set(users.map((u) => u.casualWorkerId).filter(Boolean));
    return workers.filter((w) => w.status === 'active' && !linked.has(w.id));
  }, [workers, users]);

  const isSupervisor = form.role === 'supervisor';
  const canLink = !NO_WORKER_LINK.includes(form.role);
  const leadsCrew = isSupervisor && worker ? (worker.schedule.type === 'crew' ? worker.schedule.label : null) : undefined;
  const set = (field) => (e) => setForm((f) => ({ ...f, [field]: e.target.value }));

  function pickWorker(w) {
    setWorker(w);
    if (w) setForm((f) => ({ ...f, name: f.name || w.name }));
  }

  async function create(e) {
    e.preventDefault();
    if (form.role === 'sysadmin' && !(await confirm({
      title: `Make ${form.name || form.email} a System Admin?`,
      body: (
        <>
          <p>A System Admin can create and disable any account (including other System Admins), change crews, schedules and shift rules, and see everything. They sign in with a password and an authenticator-app code.</p>
          <p>All current System Admins will be emailed about this.</p>
        </>
      ),
      confirmLabel: 'Create System Admin'
    }))) return undefined;

    return guard(async () => {
      setError('');
      if (isSupervisor && !worker) { setError('Choose the supervisor’s worker record — every supervisor is a worker.'); return; }
      try {
        const result = await api('/api/users', { method: 'POST', body: { ...form, casualWorkerId: canLink && worker ? worker.id : null } });
        if (result.emailed) {
          toast.success(`Account created for ${form.email}. They’ve been emailed the sign-in link and a temporary password.`);
        } else {
          toast.warn(`Account created for ${form.email}, but the sign-in email couldn’t be sent.`);
          await showTemporaryPassword(confirm, { email: form.email, password: result.temporaryPassword, emailError: result.emailError });
        }
        setForm((f) => ({ ...f, name: '', email: '' }));
        setWorker(null);
        load();
      } catch (err) {
        setError(err.message);
        toast.error(`Couldn’t create the account: ${err.message}`);
      }
    });
  }

  return (
    <div className="page">
      <div className="page__head">
        <div>
          <h2 className="page__title">Users</h2>
          <p className="page__hint">
            {user.role === 'hr'
              ? 'Create accounts for shift supervisors, Finance and the Admin Assistant. A supervisor is one of the workers and leads the crew they rotate with.'
              : user.role === 'auditor'
                ? 'All portal accounts: their roles, crews, whether they’re enabled, and who is still on a temporary password. Read-only.'
                : 'All portal accounts. As System Admin you can create any role, including HR and Auditor.'}
            {' '}Accounts linked to a worker record also get a “My attendance” page.
          </p>
        </div>
      </div>

      {user.role === 'sysadmin' && users.length > 0 && activeAdmins < 2 && (
        <div className="notice">
          Only {activeAdmins === 1 ? 'one System Admin is' : 'no System Admins are'} active. Keep at least two, so the portal can still be
          run — and a lost authenticator reset — if one is away.
        </div>
      )}
      {canCreate.length === 0 && error && <div className="error">{error}</div>}
      {canCreate.length > 0 && (
      <div className="panel">
        <h3 className="panel__title">New account</h3>
        <form onSubmit={create}>
          <div className="form-row">
            <label className="field">
              Role
              <select value={form.role} onChange={set('role')}>
                {canCreate.map((r) => <option key={r} value={r}>{ROLE_LABEL[r]}</option>)}
              </select>
            </label>
            {canLink && (
              <label className="field field--grow">
                {isSupervisor ? 'Worker record (required)' : 'Worker record (optional)'}
                <WorkerPicker id="new-account-worker" workers={freeWorkers} value={worker} onPick={pickWorker} placeholder="Search a name or employee ID…" />
              </label>
            )}
          </div>
          {isSupervisor && worker && (
            <p className={`small ${leadsCrew ? 'muted' : 'error'}`} style={{ margin: '10px 0 0' }}>
              {leadsCrew
                ? <>Will lead <strong>{leadsCrew}</strong> — the crew {worker.name} rotates with.</>
                : <>{worker.name} isn’t on a crew ({worker.schedule.label}). Put them on a crew in Schedules → Workers first.</>}
            </p>
          )}
          <div className="form-row" style={{ marginTop: 14 }}>
            <label className="field">Name<input value={form.name} onChange={set('name')} required placeholder={worker ? worker.name : ''} /></label>
            <label className="field">Email<input type="email" value={form.email} onChange={set('email')} required /></label>
            <button className="btn btn--primary" disabled={creating || (isSupervisor && (!worker || !leadsCrew))}>{creating ? 'Creating…' : 'Create'}</button>
          </div>
          <p className="small muted" style={{ margin: '8px 0 0' }}>The portal makes up a temporary password and emails it to them with the sign-in link — no one else sees it. They choose their own at first sign-in.</p>
        </form>
        {error && <div className="error">{error}</div>}
      </div>
      )}

      <table className="table">
        <thead>
          <tr>{th('name', 'Name')}{th('email', 'Email')}{th('role', 'Role')}{th('crew', 'Crew')}<th /></tr>
        </thead>
        <tbody>
          {pageUsers.map((u) => (
            <UserRow
              key={u.id}
              api={api}
              account={u}
              crews={crews}
              freeWorkers={freeWorkers}
              workersById={workersById}
              canEdit={canCreate.includes(u.role) && u.id !== user.id}
              canDisable={!(u.role === 'sysadmin' && u.active && activeAdmins <= 1)}
              onSaved={load}
            />
          ))}
        </tbody>
      </table>
      {pager}
    </div>
  );
}
